// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'3b3537405ce0d244914c12bf514539c621bec2847adda491f5c6ad3ea69400db'>;
export type ExecutionHash =
  ExecutionHashBase<'9feb737f53237aa512078a1ec3aad6aafcab898d4866a13657d304916236780e'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Application: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly jobId: CodecTypes['pg/text@1']['output'];
      readonly fullName: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly resumeUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Company: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly logoUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly bgColor: CodecTypes['pg/text@1']['output'] | null;
      readonly industry: CodecTypes['pg/text@1']['output'] | null;
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly employees: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Job: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly companyId: CodecTypes['pg/text@1']['output'];
      readonly location: CodecTypes['pg/text@1']['output'];
      readonly salary: CodecTypes['pg/text@1']['output'] | null;
      readonly jobType: 'FULL_TIME' | 'PART_TIME' | 'INTERNSHIP' | 'CONTRACT';
      readonly workplaceType: 'REMOTE' | 'HYBRID' | 'ON_SITE';
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly isFeatured: CodecTypes['pg/bool@1']['output'];
      readonly dueDate: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Testimonial: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly quote: CodecTypes['pg/text@1']['output'];
      readonly authorName: CodecTypes['pg/text@1']['output'];
      readonly authorRole: CodecTypes['pg/text@1']['output'];
      readonly authorCompanyOrSchool: CodecTypes['pg/text@1']['output'];
      readonly rating: CodecTypes['pg/int4@1']['output'];
      readonly avatarColor: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Application: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly jobId: CodecTypes['pg/text@1']['input'];
      readonly fullName: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly resumeUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Company: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly logoUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly bgColor: CodecTypes['pg/text@1']['input'] | null;
      readonly industry: CodecTypes['pg/text@1']['input'] | null;
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly employees: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Job: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly companyId: CodecTypes['pg/text@1']['input'];
      readonly location: CodecTypes['pg/text@1']['input'];
      readonly salary: CodecTypes['pg/text@1']['input'] | null;
      readonly jobType: 'FULL_TIME' | 'PART_TIME' | 'INTERNSHIP' | 'CONTRACT';
      readonly workplaceType: 'REMOTE' | 'HYBRID' | 'ON_SITE';
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly isFeatured: CodecTypes['pg/bool@1']['input'];
      readonly dueDate: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Testimonial: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly quote: CodecTypes['pg/text@1']['input'];
      readonly authorName: CodecTypes['pg/text@1']['input'];
      readonly authorRole: CodecTypes['pg/text@1']['input'];
      readonly authorCompanyOrSchool: CodecTypes['pg/text@1']['input'];
      readonly rating: CodecTypes['pg/int4@1']['input'];
      readonly avatarColor: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly application: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly fullName: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly jobId: CodecTypes['pg/text@1']['output'];
      readonly resumeUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly status: CodecTypes['pg/text@1']['output'];
    };
    readonly company: {
      readonly bgColor: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly employees: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly industry: CodecTypes['pg/text@1']['output'] | null;
      readonly logoUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly job: {
      readonly companyId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly dueDate: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly isFeatured: CodecTypes['pg/bool@1']['output'];
      readonly jobType: 'FULL_TIME' | 'PART_TIME' | 'INTERNSHIP' | 'CONTRACT';
      readonly location: CodecTypes['pg/text@1']['output'];
      readonly salary: CodecTypes['pg/text@1']['output'] | null;
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly workplaceType: 'REMOTE' | 'HYBRID' | 'ON_SITE';
    };
    readonly testimonial: {
      readonly authorCompanyOrSchool: CodecTypes['pg/text@1']['output'];
      readonly authorName: CodecTypes['pg/text@1']['output'];
      readonly authorRole: CodecTypes['pg/text@1']['output'];
      readonly avatarColor: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly quote: CodecTypes['pg/text@1']['output'];
      readonly rating: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly application: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly fullName: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly jobId: CodecTypes['pg/text@1']['input'];
      readonly resumeUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly status: CodecTypes['pg/text@1']['input'];
    };
    readonly company: {
      readonly bgColor: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly employees: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly industry: CodecTypes['pg/text@1']['input'] | null;
      readonly logoUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly job: {
      readonly companyId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly dueDate: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly isFeatured: CodecTypes['pg/bool@1']['input'];
      readonly jobType: 'FULL_TIME' | 'PART_TIME' | 'INTERNSHIP' | 'CONTRACT';
      readonly location: CodecTypes['pg/text@1']['input'];
      readonly salary: CodecTypes['pg/text@1']['input'] | null;
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly workplaceType: 'REMOTE' | 'HYBRID' | 'ON_SITE';
    };
    readonly testimonial: {
      readonly authorCompanyOrSchool: CodecTypes['pg/text@1']['input'];
      readonly authorName: CodecTypes['pg/text@1']['input'];
      readonly authorRole: CodecTypes['pg/text@1']['input'];
      readonly avatarColor: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly quote: CodecTypes['pg/text@1']['input'];
      readonly rating: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly application: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly jobId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly fullName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly resumeUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'application_jobId_idx_623c8f77';
                  readonly prefix: 'application_jobId_idx';
                  readonly columns: readonly ['jobId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'application';
                    readonly columns: readonly ['jobId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'job';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly company: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly logoUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly bgColor: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'bg-slate-900'>;
                  };
                };
                readonly industry: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'Technology'>;
                  };
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly employees: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', '500-1,000 emp'>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly job: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly companyId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly location: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly salary: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly jobType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'FULL_TIME'>;
                  };
                };
                readonly workplaceType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'HYBRID'>;
                  };
                };
                readonly tags: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly isFeatured: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly dueDate: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'job_companyId_idx_33acc5ed';
                  readonly prefix: 'job_companyId_idx';
                  readonly columns: readonly ['companyId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'job';
                    readonly columns: readonly ['companyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'company';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly testimonial: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quote: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly authorName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly authorRole: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly authorCompanyOrSchool: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly rating: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 5>;
                  };
                };
                readonly avatarColor: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'bg-indigo-600'>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly JobType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'CONTRACT'];
            };
            readonly WorkplaceType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['REMOTE', 'HYBRID', 'ON_SITE'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly company: { readonly namespace: 'public' & NamespaceId; readonly model: 'Company' };
    readonly job: { readonly namespace: 'public' & NamespaceId; readonly model: 'Job' };
    readonly testimonial: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Testimonial';
    };
    readonly application: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Application';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Application: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly jobId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fullName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly resumeUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly job: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Job' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['jobId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'application';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly jobId: { readonly column: 'jobId' };
                readonly fullName: { readonly column: 'fullName' };
                readonly email: { readonly column: 'email' };
                readonly resumeUrl: { readonly column: 'resumeUrl' };
                readonly status: { readonly column: 'status' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Company: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly logoUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly bgColor: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly industry: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly employees: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly jobs: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Job' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['companyId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'company';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly logoUrl: { readonly column: 'logoUrl' };
                readonly bgColor: { readonly column: 'bgColor' };
                readonly industry: { readonly column: 'industry' };
                readonly description: { readonly column: 'description' };
                readonly employees: { readonly column: 'employees' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Job: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly companyId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly location: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly salary: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly jobType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly workplaceType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tags: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly isFeatured: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly dueDate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly applications: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Application';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['jobId'];
                };
              };
              readonly company: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Company';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['companyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'job';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly title: { readonly column: 'title' };
                readonly companyId: { readonly column: 'companyId' };
                readonly location: { readonly column: 'location' };
                readonly salary: { readonly column: 'salary' };
                readonly jobType: { readonly column: 'jobType' };
                readonly workplaceType: { readonly column: 'workplaceType' };
                readonly tags: { readonly column: 'tags' };
                readonly isFeatured: { readonly column: 'isFeatured' };
                readonly dueDate: { readonly column: 'dueDate' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Testimonial: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quote: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly authorName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly authorRole: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly authorCompanyOrSchool: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rating: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly avatarColor: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'testimonial';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly quote: { readonly column: 'quote' };
                readonly authorName: { readonly column: 'authorName' };
                readonly authorRole: { readonly column: 'authorRole' };
                readonly authorCompanyOrSchool: { readonly column: 'authorCompanyOrSchool' };
                readonly rating: { readonly column: 'rating' };
                readonly avatarColor: { readonly column: 'avatarColor' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly JobType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'FULL_TIME'; readonly value: 'FULL_TIME' },
              { readonly name: 'PART_TIME'; readonly value: 'PART_TIME' },
              { readonly name: 'INTERNSHIP'; readonly value: 'INTERNSHIP' },
              { readonly name: 'CONTRACT'; readonly value: 'CONTRACT' },
            ];
          };
          readonly WorkplaceType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'REMOTE'; readonly value: 'REMOTE' },
              { readonly name: 'HYBRID'; readonly value: 'HYBRID' },
              { readonly name: 'ON_SITE'; readonly value: 'ON_SITE' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'application';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'company';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'job';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'testimonial';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
