import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  // Optional: define CSS variable name if using with Tailwind CSS
  variable: '--font-inter', 
});

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="min-h-screen bg-gray-50">
        {children}
      </body>
    </html>
  );
}
